# Practicing Regression Decision Tree


## importing moduls


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## loading dataset


In [2]:
df = pd.read_csv("reg_dataset.csv")
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [3]:
X = df.iloc[:, :-1].to_numpy()
y = df.iloc[:, -1].to_numpy()

print(X[:5], type(X))
print(y[:5], type(y))

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 [  20.86   57.32 1010.24   76.64]
 [  10.82   37.5  1009.23   96.62]] <class 'numpy.ndarray'>
[463.26 444.37 488.56 446.48 473.9 ] <class 'numpy.ndarray'>


## spliting dataset


In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

print("len of all splits, X_train X_test y_train y_test")
print(len(X_train),len(X_test),len(y_train),len(y_test))

len of all splits, X_train X_test y_train y_test
7654 1914 7654 1914


## traning model

In [6]:
from sklearn.tree import DecisionTreeRegressor

reg_dtree = DecisionTreeRegressor()
reg_dtree.fit(X_train,y_train)
print("Traning Done!!!")

Traning Done!!!


## predection

In [7]:
# predections from the model
y_pred_test = reg_dtree.predict(X_test)

In [8]:
# let's see the predections and actual values
np.set_printoptions(precision = 2)
print(f"y_pred_test: {y_pred_test[:5]}")
print(f"y_test: {y_test[:5]}")

y_pred_test: [451.77 440.   439.74 474.07 446.54]
y_test: [456.57 438.7  436.09 468.09 443.66]


In [9]:
# mean square error
print(f"mse: {np.sum(y_pred_test - y_test) ** 2}")

mse: 35755.028100000316


## score of model

In [10]:
from sklearn.metrics import r2_score

print(f"score train: {r2_score(y_train,reg_dtree.predict(X_train))}")
print(f"score test: {r2_score(y_test,y_pred_test)}")

score train: 1.0
score test: 0.9348675219253857
