# Practicing Regression SVR


## importing moduls


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## loading dataset


In [11]:
df = pd.read_csv("reg_dataset.csv")
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [46]:
X = df.iloc[:, :-1].to_numpy()
y = df.iloc[:, -1].to_numpy()

print(X[:5], type(X))
print(y[:5], type(y))

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 [  20.86   57.32 1010.24   76.64]
 [  10.82   37.5  1009.23   96.62]] <class 'numpy.ndarray'>
[463.26 444.37 488.56 446.48 473.9 ] <class 'numpy.ndarray'>


## spliting dataset


In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

print("len of all splits, X_train X_test y_train y_test")
print(len(X_train),len(X_test),len(y_train),len(y_test))

len of all splits, X_train X_test y_train y_test
7654 1914 7654 1914


## Standard Scaling

In [48]:
from sklearn.preprocessing import StandardScaler
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_train_scaled = scaler_X.fit_transform(X_train)
y_train_scaled = scaler_y.fit_transform(y_train.reshape(len(y_train),1)) # [1,2,..] --> [[1],[2]..]
y_train_scaled = y_train_scaled.flatten()
# print(y_train_scaled)

## traning model

In [49]:
from sklearn.svm import SVR

reg_svr = SVR(kernel='rbf')
reg_svr.fit(X_train_scaled,y_train_scaled)

SVR()

## predection

In [50]:
# predections from the model
y_pred_test = scaler_y.inverse_transform(reg_svr.predict(scaler_X.transform(X_test)).reshape(1,-1)).flatten()

In [51]:
# let's see the predections and actual values
np.set_printoptions(precision = 2)
print(f"y_pred_test: {y_pred_test[:5]}")
print(f"y_test: {y_test[:5]}")

y_pred_test: [456.17 442.81 440.86 475.63 443.81]
y_test: [456.57 438.7  436.09 468.09 443.66]


In [52]:
# mean square error
print(f"mse: {np.sum(y_pred_test - y_test) ** 2}")

mse: 62698.69730817151


## score of model

In [55]:
from sklearn.metrics import r2_score

print(f"score train: {r2_score(y_train,scaler_y.inverse_transform(reg_svr.predict(scaler_X.transform(X_train)).reshape(1,-1)).flatten())}")
print(f"score test: {r2_score(y_test,y_pred_test)}")

score train: 0.9447505885489922
score test: 0.9504108956676403
